source 'https://rubygems.org'
gem "acts-as-taggable-on", "~> 3.4"
gem "vcard", "~> 0.2.8"
gem "spreadsheet", "~> 0.6.8"
if RUBY_VERSION > '1.9'
  gem "money", "~> 5.1.0"
else
  gem "money", "~> 5.0.0"
end
