production:
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET'] %>
  folder: <%= ENV['S3_FOLDER'] %>
  endpoint: <%= ENV['S3_ENDPOINT'] %>
  secure: <%= ENV['S3_SECURE'] %>
  private: <%= ENV['S3_PRIVATE'] %>
  expires: <%= ENV['S3_EXPIRES'] %>
  proxy: <%= ENV['S3_PROXY'] %>
  thumb_folder: <%= ENV['S3_THUMB_FOLDER'] %>

development:
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET'] %>
  folder: <%= ENV['S3_FOLDER'] %>
  endpoint: <%= ENV['S3_ENDPOINT'] %>
  secure: <%= ENV['S3_SECURE'] %>
  private: <%= ENV['S3_PRIVATE'] %>
  expires: <%= ENV['S3_EXPIRES'] %>
  proxy: <%= ENV['S3_PROXY'] %>
  thumb_folder: <%= ENV['S3_THUMB_FOLDER'] %>

# Uncomment this to run plugin tests with standart redmine script
# test:
#   access_key_id:
#   secret_access_key:
#   bucket:
